### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by TylerLeonhardt** [markwragg/PowerShell-Lumos#1]
Adding macOS support to this module would be awesome!

Using this to toggle light/dark theme:
```
osascript -e 'tell application \"System Events\" to tell appearance preferences to set dark mode to not dark mode'
```

and using this to determine current theme:

```
defaults read -globalDomain AppleInterfaceStyle
```
(`Dark` if dark theme, empty if light theme)

**Comment by markwragg** [comment]
I've added this as of version 1.0.22 of the module. I haven't tested it on a MacOS yet and probably won't get to for a little while, but if you happen to want to test it that would be helpful!

It doesn't support getting your gelocation like on Windows, so needs you to specify either `-Dark` or `-Light`. I have however added support for modifying your wallpaper if you provide a path to one (set to "current desktop", but maybe needs to be every desktop?) -- again this is untested.

**Comment by markwragg** [comment]
Actually was able to test this on a Mac sooner than I thought and it wasn't quite working as I expected, just publishing a fixed version now.

**Comment by markwragg** [comment]
As of version 1.0.24 the theme switch is working now. Having realised that the code you gave me just switches it to whatever it currently isn't, i've made it so calling Invoke-Lumos on its on on MacOS will switch to the opposite theme, and now calling -Dark or -Light will always set it to those.

The wallpaper setting script isn't working, will debug that later.

**Comment by markwragg** [comment]
Wallpaper config is now working. Please give it a go and let me know if you find any issues. I've only tested it on Mojave (10.14.6) via a 2015 Macbook Pro.
