### ISSUE TITLE
More detailed installation instructions

### ISSUE THREAD

**Issue by vRobM** [markwragg/PowerShell-Lumos#10]
Howdy,

If a user not familiar with powershell or one that needs to install it tries this, it's a !comedy of errors.

Since I closed my PS window already, here's my best recollection. 

One must first have or install PS
Run PS CLI, there are 4 options, which will be confusing (ie not ISE)
Set-ExceptionPolicy to something permissive to install Lumos (maybe just for the CurrentUser Scope)
Invoke-Lumos -Dark (finally)

If this can be scripted and automated, even better, then release a .ps1 they can simply right click from explorer and choose 'Run with PowerShell'

**Comment by markwragg** [comment]
I think there's a limit to how much of that should be part of the documentation here vs users getting a basic understanding/comfort level with PowerShell before they start using 3rd party tools.
