### ISSUE TITLE
Feature request: Provide support for Office ProPlus

### ISSUE THREAD

**Issue by appieschot** [markwragg/PowerShell-Lumos#6]
I would love to have my Office client switch as well. We could implement an additional flag `includeOfficeProPlus` and set the theme registry for Office accordingly: 
`Computer\HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\UI Theme` (value would be 0 for colorfull (default light theme) and 4 for dark theme.

I am more than happy yo submit a PR for that if you want. But wanted to check if you are not already working on it.

**Comment by markwragg** [comment]
A PR would be very welcome, it’s not something I’m working on atm.

Mark
